package com.addressbook;

public enum SearchUpdateAndDeleteBy {
    SORT_BY_FIRST_NAME,SORT_BY_LAST_NAME,SORT_BY_CITY,SORT_BY_STATE,SORT_BY_PHONENUMBER,
    SORT_BY_PINCODE,
    UPDATE_LAST_NAME, UPDATE_CITY, UPDATE_STATE, UPDATE_PHONENUMBER,
    UPDATE_PINCODE,UPDATE_ADDRESS,
}
